export enum PositionEnum {

    TECH_LEAD,
    SENIOR_SOFTWARE_DEVELOPER,
    INTERMEDIATE_SOFTWARE_DEVELOPER,
    WEB_DEVELOPER,
    SYSTEM_ANALYST,
    SOFTWARE_ENGINEER,
    SENIOR_SOFTWARE_ENGINEER
}
