export enum SoftSkillEnum {

    TEAM_WORK,
    COLLABORATION,
    COMMITMENT,
    CRITICAL_THINKING,
    SELF_LEARNING,
    ADAPTABILITY,
    COMMUNICATION,
    TIME_MANAGEMENT,
    RESILIENCE,
    PROBLEM_SOLVING,
    LEADERSHIP,
    ATTENTION_TO_DETAIL

}
