export enum WorkExperienceEnum {

    OPUS_SENIOR_TECH_LEAD,
    OPUS_INTERMEDIATE_DEVELOPER,
    AUDAXWARE,
    OPUS_JR_SYSTEM_ANALYST,
    UBER_SOFTWARE_ENGINEER,
    UBER_SENIOR_SOFTWARE_ENGINEER,
}
