export enum WorkExperienceTechnologyEnum {

    JAVA_11 = "Java11",
    SPRING_BOOT = "Spring Boot",
    ANGULAR_6 = "Angular 6",
    POSTGRESQL = "POstgreSQL",
    AWS = "AWS",
    GIT = "Git",
    JIRA = "Jira",
    SCRUM = "Scrum",
    JENKINS = "Jenkins",
    SONAR_QUBE = "SonarQube",
    JAVA_8 = "Java8",
    ANGULAR_2 = "Angular 2",
    MY_SQL = "My SQL",
    C_SHARP = "C#",
    SQL_SERVER = "SQL Server",
    ANGULAR_JS = "AngularJS",
    KENDO_UI = "Kendo UI",
    MATERIAL = "Material",
    AZURE = "Azure",
    WEB_JOB = "Web Job",
    TFS = "TFS",
    KANBAN = "Kanban",
    KNOCKOUT = "Knockout",
    BOOTSTRAP = "Bootstrap",
    GO = "GoLang",
    KIBANA = "Kibana",
    GRAFANA = "Grafana",
    CPLUS2 = "C++",
    LUA = "Lua",
    M3 = "M3",
    CASSANDRA = "Cassandra",
    PHABRICATOR = "Phabricator",
    ARCANIST = "Arcanist",
    CICD = "CI/CD",
    OAUTH20 = "OAuth 2.0"
}
